
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://poegtnqqischzoehixnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvZWd0bnFxaXNjaHpvZWhpeG52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNTc4OTgsImV4cCI6MjA1OTczMzg5OH0.ggSGPSPTWI0G2URnC-XRxoWWTdeiCUPB4Hb_B_xfh_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
